# Generated by Django 3.2 on 2022-06-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='员工姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('detail', models.CharField(max_length=256, verbose_name='具体信息')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18, verbose_name='账号')),
                ('pwd', models.CharField(max_length=18, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户员工',
                'verbose_name_plural': '用户员工',
            },
        ),
    ]
