# Generated by Django 3.2 on 2022-06-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userinfo',
            new_name='MyUser',
        ),
    ]
